"""baseline

Revision ID: 7387f2685758
Revises: 
Create Date: 2026-03-29 10:10:38.128510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7387f2685758'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('profile_path', sa.String(), nullable=True),
    sa.Column('target_page', sa.String(), nullable=True),
    sa.Column('target_pages', sa.String(), nullable=True),
    sa.Column('login_status', sa.String(), nullable=True),
    sa.Column('login_started_at', sa.Integer(), nullable=True),
    sa.Column('login_process_pid', sa.Integer(), nullable=True),
    sa.Column('last_login_check', sa.Integer(), nullable=True),
    sa.Column('login_error', sa.String(), nullable=True),
    sa.Column('niche_topics', sa.String(), nullable=True),
    sa.Column('page_niches', sa.String(), nullable=True),
    sa.Column('sleep_start_time', sa.String(), nullable=True),
    sa.Column('sleep_end_time', sa.String(), nullable=True),
    sa.Column('competitor_urls', sa.String(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=True),
    sa.Column('last_post_ts', sa.Integer(), nullable=True),
    sa.Column('consecutive_fatal_failures', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('managed_pages', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_path')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_login_status'), ['login_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_accounts_platform'), ['platform'], unique=False)

    op.create_table('affiliate_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('comment_template', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('affiliate_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_affiliate_links_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_affiliate_links_keyword'), ['keyword'], unique=True)

    op.create_table('runtime_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runtime_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runtime_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runtime_settings_key'), ['key'], unique=True)

    op.create_table('runtime_settings_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runtime_settings_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runtime_settings_audit_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runtime_settings_audit_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_runtime_settings_audit_ts'), ['ts'], unique=False)

    op.create_table('system_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_status', sa.String(), nullable=True),
    sa.Column('heartbeat_at', sa.Integer(), nullable=True),
    sa.Column('current_job_id', sa.Integer(), nullable=True),
    sa.Column('safe_mode', sa.Boolean(), nullable=True),
    sa.Column('pending_command', sa.String(), nullable=True),
    sa.Column('worker_started_at', sa.Integer(), nullable=True),
    sa.Column('engagement_status', sa.String(), nullable=True),
    sa.Column('engagement_detail', sa.String(), nullable=True),
    sa.Column('viral_min_views', sa.Integer(), nullable=True),
    sa.Column('viral_max_videos_per_channel', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_state_id'), ['id'], unique=False)

    op.create_table('discovered_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('channel_url', sa.String(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=True),
    sa.Column('keyword_used', sa.String(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('avg_views', sa.Integer(), nullable=True),
    sa.Column('post_frequency', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('discovered_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discovered_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovered_channels_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_channels_score'), ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_channels_status'), ['status'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('media_path', sa.String(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('schedule_ts', sa.Integer(), nullable=True),
    sa.Column('target_page', sa.String(), nullable=True),
    sa.Column('ai_style', sa.String(), nullable=True),
    sa.Column('brain_used', sa.String(), nullable=True),
    sa.Column('ai_reasoning', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('tries', sa.Integer(), nullable=True),
    sa.Column('max_tries', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('external_post_id', sa.String(), nullable=True),
    sa.Column('dedupe_key', sa.String(), nullable=True),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('processed_media_path', sa.String(), nullable=True),
    sa.Column('post_url', sa.String(), nullable=True),
    sa.Column('view_24h', sa.Integer(), nullable=True),
    sa.Column('metrics_checked', sa.Boolean(), nullable=True),
    sa.Column('last_metrics_check_ts', sa.Integer(), nullable=True),
    sa.Column('tracking_code', sa.String(), nullable=True),
    sa.Column('tracking_url', sa.String(), nullable=True),
    sa.Column('affiliate_url', sa.String(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('parent_job_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.Integer(), nullable=True),
    sa.Column('auto_comment_text', sa.String(), nullable=True),
    sa.Column('locked_at', sa.Integer(), nullable=True),
    sa.Column('last_heartbeat_at', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.Integer(), nullable=True),
    sa.Column('finished_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('idx_jobs_account_status', ['account_id', 'status'], unique=False)
        batch_op.create_index('idx_jobs_dedupe_unique', ['account_id', 'dedupe_key'], unique=True)
        batch_op.create_index('idx_jobs_metrics', ['status', 'metrics_checked', 'finished_at'], unique=False)
        batch_op.create_index('idx_jobs_status_schedule', ['status', 'schedule_ts'], unique=False)
        batch_op.create_index('idx_jobs_tracking_unique', ['tracking_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_jobs_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_finished_at'), ['finished_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_last_heartbeat_at'), ['last_heartbeat_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_last_metrics_check_ts'), ['last_metrics_check_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_schedule_ts'), ['schedule_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_tracking_code'), ['tracking_code'], unique=False)

    op.create_table('page_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('page_url', sa.String(), nullable=False),
    sa.Column('page_name', sa.String(), nullable=True),
    sa.Column('post_url', sa.String(), nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('published_date', sa.String(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_insights_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_insights_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_insights_page_url'), ['page_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_insights_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_insights_post_url'), ['post_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_insights_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_insights_views'), ['views'], unique=False)

    op.create_table('viral_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('scraped_by_account_id', sa.Integer(), nullable=True),
    sa.Column('target_page', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scraped_by_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('viral_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_viral_materials_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_viral_materials_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_viral_materials_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_viral_materials_url'), ['url'], unique=True)
        batch_op.create_index(batch_op.f('ix_viral_materials_views'), ['views'], unique=False)

    op.create_table('job_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('ts', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('meta_json', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_events_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_events_job_id'))
        batch_op.drop_index(batch_op.f('ix_job_events_id'))

    op.drop_table('job_events')
    with op.batch_alter_table('viral_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_viral_materials_views'))
        batch_op.drop_index(batch_op.f('ix_viral_materials_url'))
        batch_op.drop_index(batch_op.f('ix_viral_materials_status'))
        batch_op.drop_index(batch_op.f('ix_viral_materials_platform'))
        batch_op.drop_index(batch_op.f('ix_viral_materials_id'))

    op.drop_table('viral_materials')
    with op.batch_alter_table('page_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_insights_views'))
        batch_op.drop_index(batch_op.f('ix_page_insights_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_page_insights_post_url'))
        batch_op.drop_index(batch_op.f('ix_page_insights_platform'))
        batch_op.drop_index(batch_op.f('ix_page_insights_page_url'))
        batch_op.drop_index(batch_op.f('ix_page_insights_id'))
        batch_op.drop_index(batch_op.f('ix_page_insights_account_id'))

    op.drop_table('page_insights')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_tracking_code'))
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_jobs_schedule_ts'))
        batch_op.drop_index(batch_op.f('ix_jobs_last_metrics_check_ts'))
        batch_op.drop_index(batch_op.f('ix_jobs_last_heartbeat_at'))
        batch_op.drop_index(batch_op.f('ix_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_finished_at'))
        batch_op.drop_index(batch_op.f('ix_jobs_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_jobs_batch_id'))
        batch_op.drop_index('idx_jobs_tracking_unique')
        batch_op.drop_index('idx_jobs_status_schedule')
        batch_op.drop_index('idx_jobs_metrics')
        batch_op.drop_index('idx_jobs_dedupe_unique')
        batch_op.drop_index('idx_jobs_account_status')

    op.drop_table('jobs')
    with op.batch_alter_table('discovered_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovered_channels_status'))
        batch_op.drop_index(batch_op.f('ix_discovered_channels_score'))
        batch_op.drop_index(batch_op.f('ix_discovered_channels_id'))

    op.drop_table('discovered_channels')
    with op.batch_alter_table('system_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_state_id'))

    op.drop_table('system_state')
    with op.batch_alter_table('runtime_settings_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runtime_settings_audit_ts'))
        batch_op.drop_index(batch_op.f('ix_runtime_settings_audit_key'))
        batch_op.drop_index(batch_op.f('ix_runtime_settings_audit_id'))

    op.drop_table('runtime_settings_audit')
    with op.batch_alter_table('runtime_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runtime_settings_key'))
        batch_op.drop_index(batch_op.f('ix_runtime_settings_id'))

    op.drop_table('runtime_settings')
    with op.batch_alter_table('affiliate_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_affiliate_links_keyword'))
        batch_op.drop_index(batch_op.f('ix_affiliate_links_id'))

    op.drop_table('affiliate_links')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_platform'))
        batch_op.drop_index(batch_op.f('ix_accounts_name'))
        batch_op.drop_index(batch_op.f('ix_accounts_login_status'))
        batch_op.drop_index(batch_op.f('ix_accounts_is_active'))
        batch_op.drop_index(batch_op.f('ix_accounts_id'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
