"""add_ai_status_to_affiliates

Revision ID: ad3ebb5bf76c
Revises: 172e0f308558
Create Date: 2026-04-02 13:47:14.165871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad3ebb5bf76c'
down_revision: Union[str, Sequence[str], None] = '172e0f308558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliate_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_status', sa.String(), nullable=True))
        batch_op.alter_column('comment_template',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_affiliate_links_ai_status'), ['ai_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliate_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_affiliate_links_ai_status'))
        batch_op.alter_column('comment_template',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('ai_status')
    # ### end Alembic commands ###
