"""add affiliate_links table

Revision ID: aeff173572d9
Revises: 7387f2685758
Create Date: 2026-04-02 06:24:23.447260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeff173572d9'
down_revision: Union[str, Sequence[str], None] = '7387f2685758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('comment_template', sa.String(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('affiliate_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_affiliate_links_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_affiliate_links_keyword'), ['keyword'], unique=True)

    op.drop_table('_alembic_tmp_accounts')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('niche_topics',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('sleep_start_time',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('sleep_end_time',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('competitor_urls',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('managed_pages',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_accounts_profile'))
        batch_op.create_index(batch_op.f('ix_accounts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_login_status'), ['login_status'], unique=False)
        batch_op.create_unique_constraint(None, ['profile_path'])

    with op.batch_alter_table('discovered_channels', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('post_frequency',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.drop_index(batch_op.f('ix_discovered_channels_account_id'))
        batch_op.drop_index(batch_op.f('ix_discovered_channels_url_acc'))
        batch_op.create_index(batch_op.f('ix_discovered_channels_id'), ['id'], unique=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('ai_style',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'short'"))
        batch_op.alter_column('ai_reasoning',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('dedupe_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('post_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('tracking_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('tracking_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('affiliate_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('job_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'POST'"))
        batch_op.alter_column('auto_comment_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_jobs_last_metrics_check'))
        batch_op.drop_index(batch_op.f('idx_jobs_scheduled'))
        batch_op.drop_index(batch_op.f('idx_jobs_tracking'))
        batch_op.create_index(batch_op.f('ix_jobs_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_finished_at'), ['finished_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_last_heartbeat_at'), ['last_heartbeat_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_last_metrics_check_ts'), ['last_metrics_check_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_tracking_code'), ['tracking_code'], unique=False)

    with op.batch_alter_table('page_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_page_insights_platform'))
        batch_op.create_index(batch_op.f('ix_page_insights_platform'), ['platform'], unique=False)

    with op.batch_alter_table('runtime_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_runtime_settings_key'))

    with op.batch_alter_table('runtime_settings_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_runtime_settings_audit_key'))
        batch_op.drop_index(batch_op.f('idx_runtime_settings_audit_ts'))

    with op.batch_alter_table('system_state', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('worker_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('("RUNNING")'))
        batch_op.alter_column('pending_command',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('engagement_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('engagement_detail',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_system_state_id'), ['id'], unique=False)

    with op.batch_alter_table('viral_materials', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('ix_viral_materials_url'))
        batch_op.create_index(batch_op.f('ix_viral_materials_url'), ['url'], unique=True)
        batch_op.create_index(batch_op.f('ix_viral_materials_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viral_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_viral_materials_id'))
        batch_op.drop_index(batch_op.f('ix_viral_materials_url'))
        batch_op.create_index(batch_op.f('ix_viral_materials_url'), ['url'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('system_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_state_id'))
        batch_op.alter_column('engagement_detail',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('engagement_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('pending_command',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('worker_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('("RUNNING")'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('runtime_settings_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_runtime_settings_audit_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('idx_runtime_settings_audit_key'), ['key'], unique=False)

    with op.batch_alter_table('runtime_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_runtime_settings_key'), ['key'], unique=False)

    with op.batch_alter_table('page_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_insights_platform'))
        batch_op.create_index(batch_op.f('idx_page_insights_platform'), ['platform'], unique=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_tracking_code'))
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_jobs_last_metrics_check_ts'))
        batch_op.drop_index(batch_op.f('ix_jobs_last_heartbeat_at'))
        batch_op.drop_index(batch_op.f('ix_jobs_finished_at'))
        batch_op.drop_index(batch_op.f('ix_jobs_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_jobs_batch_id'))
        batch_op.create_index(batch_op.f('idx_jobs_tracking'), ['tracking_code'], unique=False)
        batch_op.create_index(batch_op.f('idx_jobs_scheduled'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_jobs_last_metrics_check'), ['last_metrics_check_ts'], unique=False)
        batch_op.alter_column('auto_comment_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('job_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'POST'"))
        batch_op.alter_column('affiliate_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('tracking_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('tracking_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('post_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('dedupe_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ai_reasoning',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ai_style',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'short'"))

    with op.batch_alter_table('discovered_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovered_channels_id'))
        batch_op.create_index(batch_op.f('ix_discovered_channels_url_acc'), ['channel_url', 'account_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_discovered_channels_account_id'), ['account_id'], unique=False)
        batch_op.alter_column('score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('post_frequency',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_accounts_login_status'))
        batch_op.drop_index(batch_op.f('ix_accounts_is_active'))
        batch_op.create_index(batch_op.f('idx_accounts_profile'), ['profile_path'], unique=1)
        batch_op.alter_column('managed_pages',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('competitor_urls',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('sleep_end_time',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('sleep_start_time',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('niche_topics',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.create_table('_alembic_tmp_accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('platform', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('daily_limit', sa.INTEGER(), nullable=True),
    sa.Column('cooldown_seconds', sa.INTEGER(), nullable=True),
    sa.Column('last_post_ts', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.INTEGER(), nullable=True),
    sa.Column('consecutive_fatal_failures', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('login_status', sa.VARCHAR(), server_default=sa.text("'NEW'"), nullable=True),
    sa.Column('login_started_at', sa.INTEGER(), nullable=True),
    sa.Column('login_process_pid', sa.INTEGER(), nullable=True),
    sa.Column('last_login_check', sa.INTEGER(), nullable=True),
    sa.Column('login_error', sa.VARCHAR(), nullable=True),
    sa.Column('profile_path', sa.VARCHAR(), nullable=True),
    sa.Column('niche_topics', sa.VARCHAR(), nullable=True),
    sa.Column('sleep_start_time', sa.VARCHAR(), nullable=True),
    sa.Column('sleep_end_time', sa.VARCHAR(), nullable=True),
    sa.Column('competitor_urls', sa.VARCHAR(), nullable=True),
    sa.Column('target_page', sa.VARCHAR(), nullable=True),
    sa.Column('managed_pages', sa.VARCHAR(), nullable=True),
    sa.Column('target_pages', sa.VARCHAR(), nullable=True),
    sa.Column('page_niches', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_path', name=op.f('uq_accounts_profile_path'))
    )
    with op.batch_alter_table('affiliate_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_affiliate_links_keyword'))
        batch_op.drop_index(batch_op.f('ix_affiliate_links_id'))

    op.drop_table('affiliate_links')
    # ### end Alembic commands ###
