"""add threads interaction table

Revision ID: e806f6ae8107
Revises: 56cd7b34219d
Create Date: 2026-04-25 08:29:51.518638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e806f6ae8107'
down_revision: Union[str, Sequence[str], None] = '56cd7b34219d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threads_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_threads_interaction_dedup', 'threads_interactions', ['account_id', 'thread_id'], unique=True)
    op.create_index(op.f('ix_threads_interactions_account_id'), 'threads_interactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_threads_interactions_id'), 'threads_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_threads_interactions_thread_id'), 'threads_interactions', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threads_interactions_thread_id'), table_name='threads_interactions')
    op.drop_index(op.f('ix_threads_interactions_id'), table_name='threads_interactions')
    op.drop_index(op.f('ix_threads_interactions_account_id'), table_name='threads_interactions')
    op.drop_index('idx_threads_interaction_dedup', table_name='threads_interactions')
    op.drop_table('threads_interactions')
    # ### end Alembic commands ###
