#!/usr/bin/env python3
"""
graphql_inspector.py — Lục tung GraphQL của Meta trong quá trình đăng Reel.

Cách dùng:
    cd /home/vu/toolsauto
    python scratch/graphql_inspector.py

Kết quả được lưu vào: scratch/graphql_dump.json
Script sẽ:
  1. Mở browser với profile fb_acc_01_profile
  2. Đăng ký listener bắt MỌI response từ /api/graphql/
  3. Chờ 120s để anh thao tác upload Reel thủ công trên browser
  4. Dump toàn bộ payload + response ra file JSON để phân tích

Author: Auto-generated by Antigravity
"""
from __future__ import annotations

import sys
import json
import time
import threading
from pathlib import Path

# ── path setup ──────────────────────────────────────────────────────────────
_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_root))

from playwright.sync_api import sync_playwright, Response

# ── config ───────────────────────────────────────────────────────────────────
PROFILE_PATH    = str(_root / "content" / "profiles" / "facebook_4")
OUTPUT_FILE     = _root / "scratch" / "graphql_dump.json"
CAPTURE_SECONDS = 180   # Giây chờ để anh thao tác (tăng nếu cần)
GRAPHQL_URL_KEY = "/api/graphql"

# ── collector ─────────────────────────────────────────────────────────────────
captured: list[dict] = []
_lock = threading.Lock()

INTERESTING_KEYWORDS = [
    "story_create", "story", "reel", "video_publish", "post",
    "composer", "video", "permalink", "feedback_id", "legacy_api_post_id",
    "id", "url", "permalink_url", "post_id", "reel_id",
]

def _deep_search(obj, found=None):
    """Đào sâu vào JSON, tìm mọi key có thể chứa post/reel ID hoặc URL."""
    if found is None:
        found = {}
    if isinstance(obj, dict):
        for k, v in obj.items():
            if any(kw in k.lower() for kw in INTERESTING_KEYWORDS):
                found[k] = v
            _deep_search(v, found)
    elif isinstance(obj, list):
        for item in obj:
            _deep_search(item, found)
    return found


def on_response(response: Response):
    """Handler: bắt mọi response từ FB GraphQL."""
    if GRAPHQL_URL_KEY not in response.url:
        return

    try:
        # Bỏ qua nếu không phải JSON
        ct = response.headers.get("content-type", "")
        if "json" not in ct and "javascript" not in ct:
            return

        body = response.json()
    except Exception:
        # Thử parse text nếu json() fail (FB đôi khi trả multi-line JSON)
        try:
            raw = response.text()
            # FB đôi khi trả nhiều JSON objects trên từng dòng
            lines = [l.strip() for l in raw.split("\n") if l.strip()]
            body = []
            for line in lines:
                try:
                    body.append(json.loads(line))
                except Exception:
                    pass
            if not body:
                return
        except Exception:
            return

    # Lấy request info
    req = response.request
    try:
        post_data_raw = req.post_data or ""
        # Parse form-encoded
        req_params = {}
        for part in post_data_raw.split("&"):
            if "=" in part:
                k, _, v = part.partition("=")
                from urllib.parse import unquote_plus
                req_params[unquote_plus(k)] = unquote_plus(v)
    except Exception:
        req_params = {}

    doc_id    = req_params.get("doc_id", "?")
    fb_api_req_friendly_name = req_params.get("fb_api_req_friendly_name", "unknown")
    variables_raw = req_params.get("variables", "{}")

    try:
        variables = json.loads(variables_raw)
    except Exception:
        variables = variables_raw

    # Extract thông tin hữu ích từ response
    interesting = {}
    if isinstance(body, dict):
        interesting = _deep_search(body)
    elif isinstance(body, list):
        for b in body:
            interesting.update(_deep_search(b))

    # Chỉ lưu nếu có data (bỏ qua request thuần UI không liên quan)
    entry = {
        "timestamp":     time.strftime("%H:%M:%S"),
        "url":           response.url,
        "status":        response.status,
        "doc_id":        doc_id,
        "operation":     fb_api_req_friendly_name,
        "variables":     variables,
        "response_body": body,
        "interesting_fields": interesting,
    }

    with _lock:
        captured.append(entry)

    # In ra console ngay lập tức để anh theo dõi
    has_interesting = bool(interesting)
    marker = "🎯" if has_interesting else "📦"
    print(f"\n{marker} [{entry['timestamp']}] op={fb_api_req_friendly_name!r}  doc_id={doc_id}")
    if has_interesting:
        print("   ✅ INTERESTING FIELDS FOUND:")
        for k, v in list(interesting.items())[:20]:
            # Rút gọn value dài
            sv = str(v)
            if len(sv) > 120:
                sv = sv[:117] + "..."
            print(f"      {k}: {sv}")
    print(f"   status={response.status}  url={response.url}")


def extract_post_urls(dump: list[dict]) -> list[str]:
    """Sau khi capture, tổng hợp tất cả URL trông như post/reel."""
    urls = set()
    def _find_urls(obj):
        if isinstance(obj, str):
            if "facebook.com/reel/" in obj or "facebook.com/posts/" in obj or "/share/v/" in obj:
                urls.add(obj)
        elif isinstance(obj, dict):
            for v in obj.values():
                _find_urls(v)
        elif isinstance(obj, list):
            for item in obj:
                _find_urls(item)
    for entry in dump:
        _find_urls(entry.get("response_body"))
    return sorted(urls)


def main():
    print("=" * 70)
    print("  🔬 Meta GraphQL Inspector")
    print("=" * 70)
    print(f"  Profile   : {PROFILE_PATH}")
    print(f"  Output    : {OUTPUT_FILE}")
    print(f"  Thời gian : {CAPTURE_SECONDS}s")
    print()
    print("  📌 Hướng dẫn:")
    print("     1. Browser sẽ mở Facebook")
    print("     2. Anh THỰC HIỆN UPLOAD REEL (chọn video → nhập caption → bấm Đăng)")
    print("     3. Script tự động bắt response GraphQL")
    print("     4. Sau khi đăng xong, chờ 30s rồi script sẽ tự dump kết quả")
    print("=" * 70)
    input("\n  [ENTER] để bắt đầu mở browser...\n")

    pw = sync_playwright().start()
    context = pw.chromium.launch_persistent_context(
        user_data_dir   = PROFILE_PATH,
        headless        = False,
        viewport        = {"width": 1280, "height": 800},
        user_agent      = (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
            "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
        ),
        args = [
            "--disable-dev-shm-usage",
            "--no-sandbox",
            "--disable-gpu",
        ],
    )
    page = context.pages[0] if context.pages else context.new_page()

    # ── Đăng ký listener TRƯỚC khi navigate ──
    page.on("response", on_response)

    print(f"\n  🌐 Đang mở facebook.com...")
    page.goto("https://www.facebook.com/", wait_until="domcontentloaded")
    print(f"  ✅ Facebook đã load. BÂY GIỜ hãy UPLOAD REEL thủ công!\n")
    print(f"  ⏳ Đang capture trong {CAPTURE_SECONDS}s...")
    print(f"     (Nhấn Ctrl+C để dừng sớm)\n")

    # Countdown
    try:
        for remaining in range(CAPTURE_SECONDS, 0, -10):
            time.sleep(10)
            n = len(captured)
            print(f"  ⏳ Còn {remaining-10}s — đã bắt {n} GraphQL responses...")
    except KeyboardInterrupt:
        print("\n  ⚠️  Dừng sớm theo yêu cầu.")

    # ── Dump kết quả ──
    print(f"\n  💾 Đang lưu {len(captured)} responses vào {OUTPUT_FILE}...")

    # Tổng hợp URL tìm được
    post_urls = extract_post_urls(captured)

    summary = {
        "total_graphql_requests": len(captured),
        "unique_operations":      list({e["operation"] for e in captured}),
        "post_reel_urls_found":   post_urls,
        "entries":                captured,
    }

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2, default=str)

    print(f"\n  ✅ Đã lưu!")
    print(f"\n  📊 Tổng kết:")
    print(f"     Requests đã bắt : {len(captured)}")
    print(f"     Operations độc nhất: {len(summary['unique_operations'])}")
    print(f"     Post/Reel URLs tìm được:")
    if post_urls:
        for u in post_urls:
            print(f"       🔗 {u}")
    else:
        print("       (chưa tìm thấy — thử xem graphql_dump.json để phân tích tiếp)")

    print(f"\n  📁 File kết quả: {OUTPUT_FILE}")
    print("\n  Đóng browser...")
    try:
        context.close()
        pw.stop()
    except Exception:
        pass
    print("  Done! ✅")


if __name__ == "__main__":
    main()
